### ISSUE TITLE
Incorrect gif creation when selection extends outside of image boundary

### ISSUE THREAD

**Issue by walkerdb** [mgiraldo/Stereogranimator#1]
Hello! This is a seriously awesome project -- thanks for developing!

I was exploring the tool as used by NYPL, and noticed that occasionally what I saw in the preview gif did not match the eventual creation gif. I _think_ the issue has to do with the bounding box of the stereogram-maker extending past the edge of the actual image. In the preview this looks fine, but I suspect when the gif is made the center of the image is set based on the literal edge of the gif, instead of the creator-tool's bounding-box edge, throwing off the original positioning.

You can reproduce the bug by trying to edit [this entry](http://stereo.nypl.org/convert/16918727711?xid=2). You can stabilize the image just by extending the right edge of the right image far to the right, but the most stable point occurs when the bounding box extends past the image. Saving this results in an unusable gif.

**Comment by mgiraldo** [comment]
thanks! there is a bug in the draggable corners that lets the user drag beyond the containing image.

**Comment by mgiraldo** [comment]
f0836ba23ca431ca0287a7624b96d686850504cc fixes the more egregious situations... some edge cases still remain

**Comment by walkerdb** [comment]
Great! Thanks for the update.

**Comment by mgiraldo** [comment]
one interesting thing about this bug was that it allowed for things like: http://stereo.nypl.org/view/71887
